name: flutter_line_sdk_playground
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # riverpod
  flutter_hooks: ^0.18.2+1
  hooks_riverpod: ^1.0.3
  flutter_riverpod: ^1.0.3

  # state_notifier
  flutter_state_notifier: ^0.7.1

  # firebase
  firebase_core: ^1.13.1

  # data_base
  cloud_firestore: ^3.1.10

  # auth
  sign_in_with_apple: ^3.3.0
  firebase_auth: ^3.3.9

  # icons
  cupertino_icons: ^1.0.4
  font_awesome_flutter: ^9.2.0

  # sign_in_button
  flutter_signin_button: ^2.0.0

  # package_info
  package_info_plus: ^1.4.0

  # shared_preferences
  shared_preferences: ^2.0.13

  # introduction_screen
  introduction_screen: ^3.0.0

  # freezed_annotation
  freezed_annotation: ^1.1.0

  # native_splash
  flutter_native_splash: ^2.0.5

  # pedantic_mono
  pedantic_mono: ^1.17.0

  # device_preview
  device_preview: ^1.0.0
  flutter_line_sdk: ^2.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  freezed: ^1.1.1
  build_runner: ^2.1.7
  json_serializable: ^6.1.4
  flutter_launcher_icons: ^0.9.2

flutter:

  uses-material-design: true
